/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import com.google.gson.Gson
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse

class App {
    val ssp = SSP(systemName = getRandomWord());

    fun getRandomWord(): String {
        val client = HttpClient.newHttpClient()
        val request = HttpRequest.newBuilder()
            .uri(URI.create("https://random-word-api.herokuapp.com/word"))
            .build()

        val response = client.send(request, HttpResponse.BodyHandlers.ofString())

        // The API returns a JSON array, so we need to remove the brackets and quotes
        return response.body().removeSurrounding("[\"", "\"]").replaceFirstChar { it.uppercase() }  + " " + "Security Plan"
    }

    fun postSSP(ssp: SSP): HttpResponse<String>? {
        val url = System.getenv("REGSCALE_DOMAIN") + "/api/securityplans"
        val client = HttpClient.newHttpClient()
        val gson = Gson()
        val json = gson.toJson(ssp)

        val request = HttpRequest.newBuilder()
            .uri(URI.create(url))
            .POST(HttpRequest.BodyPublishers.ofString(json))
            .header("Content-Type", "application/json")
            // Add authorization
            .header("Authorization", System.getenv("REGSCALE_TOKEN"))
            .build()

        val response = client.send(request, HttpResponse.BodyHandlers.ofString())

        return response

    }

}

fun main() {
    for (i in 1..10){
        App().postSSP(App().ssp)
    }
}
